### ISSUE TITLE
ctx.request.body获取到的都是字符串 所以 type:'number'校验失败

### ISSUE THREAD

**Issue by shen-lan** [rojer95/egg-async-validator#1]
```		
this.UserLoginTransfer = {
			mobile: [
                {required: true, message: '手机号不能为空'},
                {type: 'number', message: '手机号必须为数字'}
            ],
			password: [
                {required: true, message: '密码不能为空'}                
            ]
		}
```
![image](https://user-images.githubusercontent.com/21122615/54593437-8bdc4180-4a69-11e9-8840-deb797c8471d.png)
这里我该如何处理？需要手动转下`number`还是怎么弄

**Comment by rojer95** [comment]
手机号码 建议用正则验证哈~

async-validator 里面写的很清楚哈

https://github.com/yiminghe/async-validator#type
number: Must be of type number.
